development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis, :url) %>
  channel_prefix: <%= Rails.application.class.parent_name.parameterize %>_<%= Rails.env %>
  password: <%= Rails.application.credentials.dig(:redis, :password) %>
